#!/bin/bash

# fail early and often
set -eEu
set -o pipefail

# define source
. CADDY_VERSION
CADDY_IMPORT_PREFIX="github.com/mholt"
CADDY_IMPORT_URL="${CADDY_IMPORT_PREFIX}"/caddy

# define Docker build context 
rm -rf target
mkdir -p target

# define Docker image name and tag
DOCKER_IMAGE=caddy
DOCKER_TAG=$CADDY_VERSION

# get caddy release
CADDY_RELEASE_ASSET_URL="https://${CADDY_IMPORT_URL}/archive/v${CADDY_VERSION}.zip"
CADDY_ARCHIVE="target/caddy-${CADDY_VERSION}.zip"
curl -L "${CADDY_RELEASE_ASSET_URL}" > "${CADDY_ARCHIVE}"

# extract caddy source to include in build context
mkdir -p "target/src/${CADDY_IMPORT_PREFIX}"
unzip -q -d "target/src/${CADDY_IMPORT_PREFIX}" "${CADDY_ARCHIVE}"

# version label needs to be removed
mv "target/src/${CADDY_IMPORT_PREFIX}/caddy-${CADDY_VERSION}" \
   "target/src/${CADDY_IMPORT_URL}"

# add other assets to build context
cp src/caddyfile target

# clean up build context
rm "${CADDY_ARCHIVE}"

# compile caddy and build docker image

docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f ./src/Dockerfile "target"

